image: registry.gitlab.com/kitsudaiki/kitsunemimi-ci-docker-images/normal-tests:1.1.0

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo Working on branch $CI_COMMIT_REF_NAME
    - pwd
    - apt-get update
    - ./build.sh test
    - mkdir upload
    - cp -r ../result/* upload/
    - cp ../build/libKitsunemimiSakuraLang/tests/functional_tests/functional_tests upload/
    - cp ../build/libKitsunemimiSakuraLang/tests/memory_leak_tests/memory_leak_tests upload/
  artifacts:
    paths:
      - upload
    expire_in: 1 week
  tags:
    - docker

tests:
  stage: test
  script:
    - ls -l
    - upload/functional_tests
  dependencies:
    - build
  tags:
    - docker

memory_leak_tests:
  stage: test
  script:
    - ls -l
    - upload/memory_leak_tests
  dependencies:
    - build
  tags:
    - docker

